// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOepcKBdku2-0S_DaHBEDrYo0x53wiCD0',
    appId: '1:703525319305:web:d1bc645c0cfcbaf3c2cc58',
    messagingSenderId: '703525319305',
    projectId: 'flutterfirebaseapp-2c7d2',
    authDomain: 'flutterfirebaseapp-2c7d2.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-2c7d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIQxLTalm0upeU4NC9T-U64i8lqNC-UEM',
    appId: '1:703525319305:android:a79d4762816d6b85c2cc58',
    messagingSenderId: '703525319305',
    projectId: 'flutterfirebaseapp-2c7d2',
    storageBucket: 'flutterfirebaseapp-2c7d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxJ9FKNZLNQKzDpbTESHWCFMPvNVJnS0',
    appId: '1:703525319305:ios:0d5fa3ae292ca060c2cc58',
    messagingSenderId: '703525319305',
    projectId: 'flutterfirebaseapp-2c7d2',
    storageBucket: 'flutterfirebaseapp-2c7d2.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSxJ9FKNZLNQKzDpbTESHWCFMPvNVJnS0',
    appId: '1:703525319305:ios:0dd296cb72683d55c2cc58',
    messagingSenderId: '703525319305',
    projectId: 'flutterfirebaseapp-2c7d2',
    storageBucket: 'flutterfirebaseapp-2c7d2.appspot.com',
    iosBundleId: 'com.example.flutterfirebaseapp.RunnerTests',
  );
}
